# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-11 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_d', '0005_auto_20170911_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
    ]
